# Generated by Django 3.2.4 on 2021-09-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixels', '0002_remove_image_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Picture',
        ),
    ]
